version: '3.1'
services:
  cadvisor: # container metric prometheus exporter
    image: gcr.io/cadvisor/cadvisor:v0.39.0
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
  mongodb-exporter:
    build: ./mongodb_exporter/
    command: ./mongodb_exporter-linux-amd64 -logtostderr -mongodb.uri mongodb://root:example@host.docker.internal:27017 -groups.enabled 'asserts,durability,background_flusshing,connections,extra_info,global_lock,index_counters,network,op_counters,op_counters_repl,memory,locks,metrics'
    restart: always
    ports:
      - 9001:9001
  loki:
    image: grafana/loki:2.4.1
    ports:
      - 3100:3100
    volumes:
      - ./loki/:/etc/loki/
    command: -config.file=/etc/loki/config.yaml
  prometheus: # metrics aggregation and alert definition server (prometheus server)
    image: prom/prometheus:v2.33.4
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/etc/prometheus/durable"
    ports:
      - 9090:9090
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
  alertmanager: # alert manager (prometheus)
    image: prom/alertmanager:v0.23.0
    volumes:
      - ./alertmanager/:/config/
    command: --config.file=/config/alertmanager.yml --log.level=debug
    ports:
      - "9093:9093"
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
  grafana: # dashboard visualisation tool (metrics & logs)
    image: grafana/grafana:8.4.3
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  wrk-injector-hello-functional: # traffic injector (low)
    image: mtchavez/docker-wrk
    profiles: [ "perf" ]
    command: wrk -t4 -c10 -d300s http://host.docker.internal:8080/hello-world
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
  wrk-injector-info-perf: # traffic injector (high)
    image: mtchavez/docker-wrk
    profiles: [ "perf" ]
    command: wrk -t4 -c1000 -d5m --timeout 1s --latency http://host.docker.internal:8080/info
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
